version: "3"
services:

  e-gifts-nginx:
    image: nginx
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    expose:
      - "8080"
    ports:
      - "80:8080"
    depends_on:
      - e-gifts-react

  e-gifts-react:
    build:
      context: "."
      dockerfile: "./docker/react/Dockerfile"
    volumes:
      - "./:/E-Gifts/www/frontend/"
    expose:
      - "3000"
