version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: "./docker/Dockerfile"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8080"
