export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";
export const USER_CLEAN_ERROR = "USER_CLEAN_ERROR";
export const USER_AUTH_EXIT = "USER_AUTH_EXIT";
