export const NAVIGATION_TOGGLE = "NAVIGATION_TOGGLE";

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";
export const USER_CLEAN_ERROR = "USER_CLEAN_ERROR";
export const USER_AUTH_EXIT = "USER_AUTH_EXIT";

export const FILTERS_SET_AVAILABLE_TAGS = "FILTERS_SET_AVAILABLE_TAGS";
export const FILTERS_SET_SELECTED_TAGS = "FILTERS_SET_SELECTED_TAGS";

export const GALLERY_VISIT = "GALLERY_VISIT";
export const GALLERY_SET_AVAILABLE_GIFTS = "GALLERY_SET_AVAILABLE_GIFTS";

export const GIFT_SET = "GIFT_SET";

export const SETTINGS_RESIZE = "SETTINGS_RESIZE";
